//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroEstacionesBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstacionServicio
    {
        public string Id { get; set; }
        public int CapacidadMaxima { get; set; }
        public string Region { get; set; }
    
        public virtual Region Region1 { get; set; }
    }
}
