//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroEstacionesBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntoCarga
    {
        public string Id { get; set; }
        public int Tipo { get; set; }
        public int CapacidadMaxima { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
    }
}
